<?php
/**
 * Mahara: Electronic portfolio, weblog, resume builder and social networking
 * Copyright (C) 2006-2011 Catalyst IT Ltd (http://www.catalyst.net.nz)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package    mahara
 * @subpackage artefact-survey
 * @author     Gregor Anzelj
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL
 * @copyright  (C) 2010-2011 Gregor Anzelj <gregor.anzelj@gmail.com>
 *
 */

define('INTERNAL', true);

require_once(dirname(dirname(dirname(dirname(__FILE__)))) . '/init.php');
define('TITLE', get_string('surveyanalysis', 'artefact.survey'));
require_once('pieforms/pieform.php');
safe_require('artefact', 'survey');


global $SESSION;
global $USER;

$survey = $SESSION->get('survey');
$filename = 'survey-responses-' . date('Ymd-Hi');

if ($survey != '') {

	$artefacts = get_records_sql_array(
		"SELECT	a.id
		FROM {artefact} a
		LEFT JOIN {artefact_access_usr} aau ON (aau.artefact = a.id)
		WHERE aau.usr = ? AND a.title = ?", array($USER->get('id'), $survey)
	);
	
	$content  = 'Survey: ' . $survey . "\n";
	$content .= 'CSV file with survey responses generated by Mahara Survey plugin.' . "\n\n";
	$header = false;

	foreach ($artefacts as $artefact) {
		$id = $artefact->id;
		$survey = null;
		try {
			$survey = artefact_instance_from_id($id);
		}
		catch (Exception $e) { }
		
		$data = unserialize($survey->get('description'));
		// Add header, if it doesn't exist...
		if (!$header) {
			$content .= ';';
			foreach ($data as $key => $value) {
				$content .= $key . ';';
			}
			$content .= "\n";
			$header = true;
		}
		
		// Add row with responses...
		$content .= 'User' . $survey->get('owner') . ';';
		foreach ($data as $key => $value) {
			$content .= $value . ';';
		}
		$content .= "\n";
	}

	header('Content-Type: text/csv; charset=utf-8');		
	header('Content-Disposition: attachment; filename=' . $filename . '.csv');
	echo $content;
}

// Unset SESSION values
$SESSION->set('survey', '');

// Stop processing the page
exit;

?>
